# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('nations', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('asset_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('overall_rating', models.IntegerField(null=True, blank=True)),
                ('card_att1', models.IntegerField(null=True, blank=True)),
                ('card_att2', models.IntegerField(null=True, blank=True)),
                ('card_att3', models.IntegerField(null=True, blank=True)),
                ('card_att4', models.IntegerField(null=True, blank=True)),
                ('card_att5', models.IntegerField(null=True, blank=True)),
                ('card_att6', models.IntegerField(null=True, blank=True)),
                ('card_type', models.IntegerField(null=True, blank=True)),
                ('item_type', models.CharField(max_length=100, blank=True)),
                ('card_set', models.CharField(max_length=100, blank=True)),
                ('shirt_number', models.IntegerField(null=True, blank=True)),
                ('dob', models.DateField(null=True, blank=True)),
                ('join_date', models.DateField(null=True, blank=True)),
                ('height', models.IntegerField(null=True, blank=True)),
                ('weight', models.IntegerField(null=True, blank=True)),
                ('role_line', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100, blank=True)),
                ('prefferred_foot', models.CharField(max_length=100)),
                ('weak_foot', models.IntegerField(null=True, blank=True)),
                ('skill_moves', models.IntegerField(null=True, blank=True)),
                ('att_workrate', models.CharField(max_length=100)),
                ('def_workrate', models.CharField(max_length=100)),
                ('acceleration', models.IntegerField(null=True, blank=True)),
                ('sprint_speed', models.IntegerField(null=True, blank=True)),
                ('agility', models.IntegerField(null=True, blank=True)),
                ('balance', models.IntegerField(null=True, blank=True)),
                ('jumping', models.IntegerField(null=True, blank=True)),
                ('stamina', models.IntegerField(null=True, blank=True)),
                ('strength', models.IntegerField(null=True, blank=True)),
                ('reactions', models.IntegerField(null=True, blank=True)),
                ('aggression', models.IntegerField(null=True, blank=True)),
                ('interceptions', models.IntegerField(null=True, blank=True)),
                ('positioning', models.IntegerField(null=True, blank=True)),
                ('vision', models.IntegerField(null=True, blank=True)),
                ('ball_control', models.IntegerField(null=True, blank=True)),
                ('crossing', models.IntegerField(null=True, blank=True)),
                ('dribbling', models.IntegerField(null=True, blank=True)),
                ('finishing', models.IntegerField(null=True, blank=True)),
                ('free_kick_accuracy', models.IntegerField(null=True, blank=True)),
                ('heading_accuracy', models.IntegerField(null=True, blank=True)),
                ('long_passing', models.IntegerField(null=True, blank=True)),
                ('short_passing', models.IntegerField(null=True, blank=True)),
                ('marking', models.IntegerField(null=True, blank=True)),
                ('long_shots', models.IntegerField(null=True, blank=True)),
                ('shot_power', models.IntegerField(null=True, blank=True)),
                ('standing_tackle', models.IntegerField(null=True, blank=True)),
                ('sliding_tackle', models.IntegerField(null=True, blank=True)),
                ('volleys', models.IntegerField(null=True, blank=True)),
                ('curve', models.IntegerField(null=True, blank=True)),
                ('penalties', models.IntegerField(null=True, blank=True)),
                ('gk_diving', models.IntegerField(null=True, blank=True)),
                ('gk_handling', models.IntegerField(null=True, blank=True)),
                ('gk_kicking', models.IntegerField(null=True, blank=True)),
                ('gk_reflexes', models.IntegerField(null=True, blank=True)),
                ('gk_positioning', models.IntegerField(null=True, blank=True)),
                ('desc', models.CharField(max_length=100, blank=True)),
                ('created', models.DateTimeField(null=True, blank=True)),
                ('modified', models.DateTimeField(null=True, blank=True)),
                ('slug', models.CharField(max_length=50, blank=True)),
                ('club', models.ForeignKey(to_field=b'asset_id', blank=True, to='clubs.Club', null=True)),
                ('league', models.ForeignKey(to_field=b'asset_id', blank=True, to='leagues.League', null=True)),
                ('nation', models.ForeignKey(to_field=b'asset_id', blank=True, to='nations.Nation', null=True)),
            ],
            options={
                'ordering': [b'-overall_rating'],
                'db_table': b'players_14',
            },
            bases=(models.Model,),
        ),
    ]
